version: "3.8"

services:
  ttt-game:
    build: .
    image: "ttt-game:latest"
    expose:
      - 8000
    env_file:
      - .env.prod
    working_dir: /home/ttt
    volumes:
      - static_volume:/home/ttt/app/static
      - $PWD/src:/home/ttt
    container_name: ttt-game

  nginx:
    build: ./nginx
    image: "ttt-nginx:latest"
    ports:
      - "8000:80"
    depends_on:
      - ttt-game
    volumes:
      - static_volume:/home/ttt/app/static
    container_name: ttt-nginx

volumes:
  static_volume:
