version: "3.8"

services:
  ttt-game:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        ENV: ${ENV}
        ROOT_FOLDER: ${ROOT_FOLDER}
        SECRET_KEY: ${SECRET_KEY}
    image: "ttt-game:latest"
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - $PWD/src:${ROOT_FOLDER}
    environment:
      - ENV=dev
      - LOG_LEVEL=debug
      - ROOT_FOLDER
      - APP_FOLDER
      - SECRET_KEY
    privileged: true
    tty: true
    container_name: ttt-game

  nginx:
    build: ./nginx
    image: "ttt-nginx:latest"
    ports:
      - "8000:80"
    depends_on:
      - ttt-game
    volumes:
      - $PWD/src/app/static:${APP_FOLDER}/static
    privileged: true
    tty: true
    container_name: ttt-nginx
