version: "3.8"

services:
  ttt-game:
    container_name: ttt-game
    image: "ttt-game:latest"
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - .env.prod
    volumes:
      - static_volume:/home/ttt/app/static

  nginx:
    container_name: ttt-nginx
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - ttt-game
    volumes:
      - static_volume:/home/ttt/app/static

volumes:
  static_volume:
