version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    env_file:
      - .env.prod
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - web
