###########
# BUILDER #
###########

# pull official base image
FROM python:3.10.1-slim-bullseye as builder

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

# install python dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels -r requirements.txt

# https://github.com/benoitc/gunicorn/pull/2581#issuecomment-994198667
RUN pip wheel --no-cache-dir --no-deps --wheel-dir /usr/src/app/wheels "https://github.com/benoitc/gunicorn/archive/refs/heads/master.zip#egg=gunicorn==20.1.0"


#########
# FINAL #
#########

# pull official base image
FROM python:3.10.1-slim-bullseye

# create directory for the app user
ARG ROOT_FOLDER
ENV ROOT=$ROOT_FOLDER
RUN mkdir -p $ROOT
WORKDIR $ROOT

# create the app user
RUN addgroup --system appuser && adduser --system --group appuser

# install dependencies
RUN apt-get update
RUN apt-get install -y nodejs npm

# install postcss-cli as a global package (knwon issue)
RUN npm install --global postcss-cli@8.3.1

# install dependencies
RUN apt-get install -y --no-install-recommends netcat
COPY --from=builder /usr/src/app/wheels /wheels
COPY --from=builder /usr/src/app/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

# chown all the files to the app user
RUN chown -R appuser:appuser $ROOT

# change to the app user
USER appuser

# run Gunicorn WSGI
# config file loaded by Gunicorn: ./gunicorn.conf.py
ENTRYPOINT ["gunicorn"]
