version: "3.8"

services:
  ttt-game:
    build: .
    image: "ttt-game:latest"
    expose:
      - 8000
    env_file:
      - .env.dev
    volumes:
      - $PWD/src:/home/ttt
    privileged: true
    tty: true
    container_name: ttt-game

  nginx:
    build: ./nginx
    image: "ttt-nginx:latest"
    ports:
      - "8000:80"
    depends_on:
      - ttt-game
    volumes:
      - $PWD/src/app/static:/home/ttt/app/static
    privileged: true
    tty: true
    container_name: ttt-nginx
